In [1]:
import os
import warnings

import pandas as pd

# Path to result data (relative to notebooks/ directory)
DATA_DIR = os.path.join(os.path.dirname(os.path.abspath("")), "result", "stat")

# Display names for methods
METHOD_DISPLAY = {
    "cls": "AS", "thd": "DT", "lrn": "LR", "ste": "STE",
    "exact": "EX", "rel": "RR", "root": "N1",
}

# Baseline methods (no param in filename)
BASELINE_METHODS = {"exact", "rel", "root"}

In [2]:
def load_results(problem, sizes, methods, penalty):
    """Load experiment results and reshape into a comparison table."""
    results = []
    for size in sizes:
        for method in methods:
            results.append(retrieve_data(problem, size, method, penalty))
    df = pd.DataFrame(results)
    return reshape_dataframe(df, problem, sizes, methods)


def retrieve_data(problem, size, method, penalty):
    """Retrieve metrics from a single experiment CSV file."""
    # Parse projection flag
    projection = method.endswith("-p")
    base_method = method[:-2] if projection else method
    display_name = METHOD_DISPLAY[base_method] + ("-P" if projection else "")

    # Build file path: baseline methods have no penalty
    size_str = str(size) if problem == "rb" else f"{size}-{size}"
    suffix = "-p" if projection else ""
    if base_method in BASELINE_METHODS:
        filename = f"{problem}_{base_method}_{size_str}{suffix}.csv"
    else:
        filename = f"{problem}_{base_method}{penalty}_{size_str}{suffix}.csv"
    csv_path = os.path.join(DATA_DIR, filename)

    # Default metrics for missing files
    metrics = {
        "Method": display_name,
        "Problem Size": size,
        "Obj Mean": None,
        "Obj Median": None,
        "% Infeasible": None,
        "% Unsolved": None,
        "Time (Sec)": None,
    }

    if not os.path.exists(csv_path):
        warnings.warn(f"File not found: {csv_path}")
        return metrics

    df = pd.read_csv(csv_path)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        metrics.update({
            "Obj Mean": df["Obj Val"].mean(),
            "Obj Median": df["Obj Val"].median(),
            "% Infeasible": (
                (df["Num Violations"] > 0).mean() * 100
                if "Num Violations" in df.columns
                else (df["Constraints Viol"] > 0).mean() * 100
            ),
            "% Unsolved": df["Obj Val"].isna().mean() * 100,
            "Time (Sec)": df["Elapsed Time"].mean(),
        })
    return metrics


def reshape_dataframe(df, problem, sizes, methods):
    """Reshape results from long format into a method x metric comparison table."""
    display_methods = [
        METHOD_DISPLAY[m[:-2]] + "-P" if m.endswith("-p") else METHOD_DISPLAY[m]
        for m in methods
    ]
    metric_names = ["Obj Mean", "Obj Median", "% Infeasible", "% Unsolved", "Time (Sec)"]

    rows = []
    for method in display_methods:
        for metric in metric_names:
            row = {"Method": method, "Metric": metric}
            for s in sizes:
                values = df[(df["Method"] == method) & (df["Problem Size"] == s)][metric].values
                if len(values) != 1:
                    raise ValueError(
                        f"Expected 1 value for {method}/{metric}/size={s}, got {len(values)}"
                    )
                col = f"{s * 2}x4" if problem == "rb" else f"{s}x{s}"
                row[col] = values[0]
            rows.append(row)
    return pd.DataFrame(rows)

### Convex Quadratic (QP)

In [3]:
sizes = [20, 50, 100, 200, 500, 1000]
methods = ["cls", "cls-p", "thd", "thd-p", "exact", "rel", "root", "lrn", "ste"]
load_results(problem="cq", sizes=sizes, methods=methods, penalty=1.0)

,Method,Metric,20x20,50x50,100x100,200x200,500x500,1000x1000
0,AS,Obj Mean,-4.879978e+00,-1.512641e+01,-1.945163e+01,-41.032806,-92.320995,-183.250237
1,AS,Obj Median,-4.917381e+00,-1.516119e+01,-1.943988e+01,-41.034512,-92.308155,-183.284159
2,AS,% Infeasible,7.800000e+01,9.000000e+01,9.800000e+01,98.000000,100.000000,100.000000
3,AS,% Unsolved,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
4,AS,Time (Sec),1.804590e-05,1.789808e-05,1.879692e-05,0.000038,0.000022,0.000022
5,AS-P,Obj Mean,-4.819501e+00,-1.508453e+01,-1.933796e+01,-40.975396,-92.144262,-182.959230
6,AS-P,Obj Median,-4.829980e+00,-1.506975e+01,-1.934205e+01,-40.979979,-92.168870,-182.995273
7,AS-P,% Infeasible,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
8,AS-P,% Unsolved,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
9,AS-P,Time (Sec),6.433816e-03,3.535104e-03,1.582677e-03,0.001099,0.000826,0.000551
10,DT,Obj Mean,-4.952768e+00,-1.532249e+01,-1.957548e+01,-41.368563,-93.585951,-185.620582
11,DT,Obj Median,-4.986632e+00,-1.536530e+01,-1.960897e+01,-41.375544,-93.667141,-185.629880
12,DT,% Infeasible,8.300000e+01,8.700000e+01,9.900000e+01,100.000000,100.000000,100.000000
13,DT,% Unsolved,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
14,DT,Time (Sec),1.729965e-05,1.756191e-05,1.859188e-05,0.000037,0.000023,0.000024
15,DT-P,Obj Mean,-4.880044e+00,-1.527423e+01,-1.950172e+01,-41.252142,-93.419035,-185.400246
16,DT-P,Obj Median,-4.915628e+00,-1.532782e+01,-1.951045e+01,-41.245990,-93.488829,-185.427430
17,DT-P,% Infeasible,3.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
18,DT-P,% Unsolved,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
19,DT-P,Time (Sec),1.666440e-01,1.296871e-02,3.111780e-03,0.000885,0.000736,0.003130
20,EX,Obj Mean,-5.120363e+00,-1.592816e+01,-2.079016e+01,NaN,NaN,NaN
21,EX,Obj Median,-5.130437e+00,-1.595632e+01,-2.077895e+01,NaN,NaN,NaN
22,EX,% Infeasible,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
23,EX,% Unsolved,0.000000e+00,0.000000e+00,0.000000e+00,100.000000,100.000000,100.000000
24,EX,Time (Sec),8.727795e+00,1.520732e+03,1.237534e+03,1234.472786,1233.198136,1244.286831
25,RR,Obj Mean,-5.179348e+00,-1.617259e+01,-2.192232e+01,-46.726894,-106.526320,-213.312114
26,RR,Obj Median,-5.216537e+00,-1.620492e+01,-2.189172e+01,-46.754793,-106.536356,-213.291925
27,RR,% Infeasible,1.000000e+02,1.000000e+02,1.000000e+02,100.000000,100.000000,100.000000
28,RR,% Unsolved,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
29,RR,Time (Sec),4.169028e-01,4.398705e-01,5.834911e-01,0.846123,2.639185,8.873510
30,N1,Obj Mean,9.806626e+07,1.695088e+17,1.549316e+18,NaN,NaN,NaN
31,N1,Obj Median,9.599920e+00,2.448033e+17,1.445539e+18,NaN,NaN,NaN
32,N1,% Infeasible,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
33,N1,% Unsolved,0.000000e+00,0.000000e+00,0.000000e+00,100.000000,100.000000,100.000000
34,N1,Time (Sec),4.145272e-01,4.975908e-01,1.042045e+02,1233.133252,1233.129785,1242.444680
35,LR,Obj Mean,-4.886124e+00,-1.532223e+01,-2.016619e+01,-43.747246,-99.328470,-197.637216
36,LR,Obj Median,-4.921752e+00,-1.533856e+01,-2.019236e+01,-43.721512,-99.335684,-197.673888
37,LR,% Infeasible,6.600000e+01,9.500000e+01,1.000000e+02,100.000000,100.000000,100.000000
38,LR,% Unsolved,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
39,LR,Time (Sec),5.962849e-06,6.029606e-06,7.724762e-06,0.000026,0.000007,0.000007
40,STE,Obj Mean,-4.764138e+00,-1.490266e+01,-1.859783e+01,-38.931893,-85.692890,-168.051700
41,STE,Obj Median,-4.783441e+00,-1.492838e+01,-1.861470e+01,-38.912752,-85.707122,-168.054755
42,STE,% Infeasible,5.700000e+01,6.200000e+01,6.000000e+01,66.000000,48.000000,11.000000
43,STE,% Unsolved,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
44,STE,Time (Sec),1.312494e-05,1.493931e-05,1.529694e-05,0.000034,0.000021,0.000022

### Simple Non-Convex

In [4]:
sizes = [20, 50, 100, 200, 500, 1000]
methods = ["cls", "cls-p", "thd", "thd-p", "exact", "rel", "root", "lrn", "ste"]
load_results(problem="nc", sizes=sizes, methods=methods, penalty=1.0)

,Method,Metric,20x20,50x50,100x100,200x200,500x500,1000x1000
0,AS,Obj Mean,-0.248311,-1.200589e+00,-2.036498,-3.578413,-4.804356,-18.082888
1,AS,Obj Median,-0.236336,-1.217822e+00,-2.040272,-3.652391,-10.075942,-18.085712
2,AS,% Infeasible,27.000000,8.100000e+01,72.000000,90.000000,93.000000,99.000000
3,AS,% Unsolved,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
4,AS,Time (Sec),0.000020,2.062559e-05,0.000020,0.000035,0.000023,0.000026
5,AS-P,Obj Mean,-0.245407,-1.186733e+00,-2.024602,-3.575743,-4.914447,-18.032323
6,AS-P,Obj Median,-0.233918,-1.201151e+00,-2.032327,-3.658996,-10.038494,-18.075630
7,AS-P,% Infeasible,0.000000,0.000000e+00,0.000000,0.000000,1.000000,0.000000
8,AS-P,% Unsolved,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
9,AS-P,Time (Sec),0.004982,5.581918e-03,0.001117,0.000820,0.163315,0.000484
10,DT,Obj Mean,-0.278060,-1.230349e+00,-2.142181,-4.114423,-9.968828,-18.045432
11,DT,Obj Median,-0.254306,-1.234236e+00,-2.134480,-4.150994,-9.958219,-18.034434
12,DT,% Infeasible,37.000000,7.700000e+01,87.000000,95.000000,97.000000,100.000000
13,DT,% Unsolved,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
14,DT,Time (Sec),0.000020,1.954794e-05,0.000020,0.000039,0.000022,0.000029
15,DT-P,Obj Mean,-0.271871,-1.210869e+00,-2.088158,-4.092158,-9.904166,-17.939936
16,DT-P,Obj Median,-0.248120,-1.213592e+00,-2.087546,-4.140750,-9.897406,-17.902825
17,DT-P,% Infeasible,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
18,DT-P,% Unsolved,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
19,DT-P,Time (Sec),0.025415,3.699743e-02,0.001692,0.001655,0.000502,0.000671
20,EX,Obj Mean,-0.453119,1.648753e+00,256.925531,NaN,NaN,NaN
21,EX,Obj Median,-0.462647,-5.236851e-02,134.620354,NaN,NaN,NaN
22,EX,% Infeasible,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
23,EX,% Unsolved,0.000000,0.000000e+00,86.000000,100.000000,100.000000,100.000000
24,EX,Time (Sec),994.912888,1.001522e+03,1000.555162,1000.356855,1001.291239,1006.278797
25,RR,Obj Mean,-0.464496,-1.039170e+00,-2.067550,-3.989610,-9.390958,NaN
26,RR,Obj Median,-0.476225,-1.214793e+00,-2.307348,-4.326802,-9.220684,NaN
27,RR,% Infeasible,97.000000,1.000000e+02,100.000000,100.000000,100.000000,0.000000
28,RR,% Unsolved,0.000000,0.000000e+00,0.000000,0.000000,0.000000,100.000000
29,RR,Time (Sec),0.996347,1.189020e+00,4.600046,54.008781,449.023858,31.147519
30,N1,Obj Mean,21321.988340,3.723283e+06,4411.446387,NaN,NaN,NaN
31,N1,Obj Median,2.222023,4.584658e+01,155.254010,NaN,NaN,NaN
32,N1,% Infeasible,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
33,N1,% Unsolved,0.000000,0.000000e+00,86.000000,100.000000,100.000000,100.000000
34,N1,Time (Sec),0.144314,8.968112e+00,940.429665,1000.345446,1001.300604,1006.367944
35,LR,Obj Mean,-0.288912,-1.349452e+00,-2.488778,-5.552735,-13.014432,-27.934520
36,LR,Obj Median,-0.277094,-1.367806e+00,-2.499929,-5.563332,-13.579985,-27.933908
37,LR,% Infeasible,39.000000,9.500000e+01,97.000000,100.000000,100.000000,100.000000
38,LR,% Unsolved,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
39,LR,Time (Sec),0.000006,6.272793e-06,0.000007,0.000026,0.000007,0.000011
40,STE,Obj Mean,-0.178104,-9.987308e-01,-1.879181,-3.112825,-6.616734,-11.069029
41,STE,Obj Median,-0.177791,-9.961143e-01,-1.887373,-3.130856,-6.614751,-11.075995
42,STE,% Infeasible,12.000000,4.800000e+01,57.000000,29.000000,7.000000,0.000000
43,STE,% Unsolved,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
44,STE,Time (Sec),0.000015,1.588583e-05,0.000017,0.000031,0.000018,0.000025

### Rosenbrock

In [5]:
sizes = [10, 100, 1000, 10000]
methods = ["cls", "cls-p", "thd", "thd-p", "exact", "rel", "root", "lrn", "ste"]
load_results(problem="rb", sizes=sizes, methods=methods, penalty=20)

,Method,Metric,20x4,200x4,2000x4,20000x4
0,AS,Obj Mean,63.402197,4.029966e+02,3.595975e+03,3.043025e+04
1,AS,Obj Median,61.957197,3.724574e+02,3.380251e+03,2.674693e+04
2,AS,% Infeasible,6.000000,0.000000e+00,4.000000e+00,4.100000e+01
3,AS,% Unsolved,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
4,AS,Time (Sec),0.000025,2.682686e-05,3.118992e-05,8.130789e-05
5,AS-P,Obj Mean,64.748065,4.029966e+02,3.637818e+03,inf
6,AS-P,Obj Median,62.258814,3.724574e+02,3.380251e+03,3.200610e+04
7,AS-P,% Infeasible,0.000000,0.000000e+00,0.000000e+00,5.000000e+00
8,AS-P,% Unsolved,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
9,AS-P,Time (Sec),0.000286,1.855779e-04,4.292130e-04,4.402836e-02
10,DT,Obj Mean,61.684106,4.793452e+02,4.271354e+03,5.433290e+04
11,DT,Obj Median,61.039455,4.678952e+02,3.940498e+03,5.035844e+04
12,DT,% Infeasible,8.000000,2.000000e+00,6.000000e+00,3.600000e+01
13,DT,% Unsolved,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
14,DT,Time (Sec),0.000025,2.507210e-05,3.272295e-05,7.851839e-05
15,DT-P,Obj Mean,64.947764,4.824445e+02,4.393142e+03,inf
16,DT-P,Obj Median,61.039455,4.678952e+02,3.940498e+03,6.445257e+04
17,DT-P,% Infeasible,0.000000,0.000000e+00,0.000000e+00,3.000000e+00
18,DT-P,% Unsolved,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
19,DT-P,Time (Sec),0.000832,3.449845e-04,6.514764e-04,9.913595e-03
20,EX,Obj Mean,64.672606,8.432504e+05,4.704699e+10,1.089649e+15
21,EX,Obj Median,59.164972,9.088066e+02,9.262093e+03,1.031457e+05
22,EX,% Infeasible,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
23,EX,% Unsolved,0.000000,0.000000e+00,4.000000e+00,2.200000e+01
24,EX,Time (Sec),1004.613147,1.002198e+03,1.001692e+03,1.040059e+03
25,RR,Obj Mean,12036.985224,1.430367e+04,2.102169e+06,1.746757e+08
26,RR,Obj Median,51.166179,5.018969e+02,5.436599e+03,7.034959e+06
27,RR,% Infeasible,41.000000,1.800000e+01,1.000000e+00,4.000000e+00
28,RR,% Unsolved,0.000000,4.200000e+01,9.300000e+01,7.800000e+01
29,RR,Time (Sec),0.557036,1.239634e+00,9.233410e+00,1.064124e+03
30,N1,Obj Mean,87.831885,3.718340e+08,8.273751e+12,1.217838e+15
31,N1,Obj Median,77.335893,9.574160e+02,9.379373e+03,1.031645e+05
32,N1,% Infeasible,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
33,N1,% Unsolved,0.000000,0.000000e+00,5.000000e+00,2.200000e+01
34,N1,Time (Sec),0.081286,2.608396e-01,7.191052e+01,7.820517e+02
35,LR,Obj Mean,67.205215,6.280650e+02,6.456956e+03,6.363268e+04
36,LR,Obj Median,63.849136,6.115598e+02,5.924706e+03,6.207497e+04
37,LR,% Infeasible,32.000000,4.900000e+01,4.500000e+01,4.000000e+01
38,LR,% Unsolved,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
39,LR,Time (Sec),0.000007,6.616116e-06,8.292198e-06,7.326603e-06
40,STE,Obj Mean,64.066460,5.988681e+02,6.542213e+03,5.593694e+04
41,STE,Obj Median,61.504997,6.117131e+02,6.150763e+03,3.364880e+04
42,STE,% Infeasible,10.000000,2.000000e+00,7.000000e+00,3.400000e+01
43,STE,% Unsolved,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
44,STE,Time (Sec),0.000020,1.968384e-05,2.205133e-05,3.880739e-05